import useTranslation from "next-translate/useTranslation";
import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  const { t } = useTranslation("index");

  return (
    <div tw="p-5">
      <Head>
        <title>Ataasil University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h2 tw="text-[40px]">{t("home.hero.title")}</h2>
    </div>
  );
}
