import useTranslation from "next-translate/useTranslation";
import Head from "next/head";
import Hero from "../components/Hero";

export default function Home() {
  const { t } = useTranslation("index");

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </div>
  );
}
