import Head from "next/head";
import styled from "styled-components";
import Logo from "../src/components/Logo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ataasil University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-2 m-5">
        <Text className="font-bold underline text-5xl ">Hello Ataasil</Text>
        <Text>
          العلم الأصيل الذي نزل من النبي صلى الله عليه وسلم إلى أصحابه وعلماء
          هذه الأمة
        </Text>
        <Logo />
      </main>
    </div>
  );
}

const Text = styled.p`
  color: var(--color-primary);
  font-weight: 800;
  font-size: 28px;
  line-height: 31px;
`;
