import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-2 m-5">
        <Text className="font-bold underline text-5xl ">Hello Ataasil</Text>
        <p>
          العلم الأصيل الذي نزل من النبي صلى الله عليه وسلم إلى أصحابه وعلماء
          هذه الأمة
        </p>
      </main>
    </div>
  );
}

const Text = styled.p`
  color: var(--color-primary);
`;
